-- NiceSim3_NoBadge -- Nice Flight! simulator macro, generated by tools/make_macros.py
-- from a REAL flight: BULL-NOSE-2026-09-16-14-29-06.csv (flight starting at 685 s).
-- 155 ft, 6:23. Nice by time. Run AFTER NiceSim2: Duration 5 is already held, so NO badges.
--
-- Run: FrSky Suite toolbar > Run Macro > pick THIS folder, then click Resume
-- (the debugger pauses on line 1). If it asks to restart the simulator to
-- load the files, click CANCEL. Have the Nice Flight! page showing.
--
-- SPEED: how much faster than real life the flight is replayed. The widget
-- must run its flight clock at the SAME rate or the flight will be measured
-- short: Nice Flight! CFG > Data > Simulator time scale = SPEED (1, 4, 8 or
-- 16). At 8x this 6:47 flight takes about 62 seconds. Set both to 1
-- to watch the Live screen in real time.
local SPEED = 8

-- Controls, as MEASURED in the simulator with sim/NiceSimDiag (2026-09-17,
-- X14, Ethos 26.1.2), reading the real sources back after each call:
--   simulator.setAnalog(1, v)  = throttle. At rest (0) the template reads the
--                                brake as pulled = Landing mode; +100 = brake off.
--   simulator.setAnalog(2, v)  = elevator (any movement leaves Zoom)
--   simulator.setSwitch(7, v)  = the launch button: +100 -> Launch mode,
--                                -100 -> Zoom until the elevator moves.
local AN_THROTTLE, AN_ELEVATOR, SW_LAUNCH = 1, 2, 7

-- Telemetry. Any module/band/rx/physId reaches the model's Altitude sensor,
-- but the simulator flags every sensor LOST within ~0.25 s unless the radio
-- link looks alive, so RSSI and VFR frames go out with every altitude frame
-- and frames never stop for longer than FRAME_GAP real seconds (at 0.1 s the
-- sensor still flapped between alive and lost; measured 2026-09-17).
local PHYS_ID = 0x1A
local ALT_APP_ID, RX_APP_ID, RSSI_APP_ID, VFR_APP_ID = 0x0100, 0xF104, 0xF101, 0xF010
local RX_CV = 500
local FRAME_GAP = 0.03           -- tightened automatically if the sensor still drops out

local BRAKED = false        -- false = hand catch: the widget ends it after 20 s on the ground
local ALT = { 8, 57, 88, 99, 102, 103, 103, 100, 97, 99, 101, 100, 102, 102, 104, 108, 108, 108, 109, 112, 109, 107, 105, 107, 105, 106, 108, 105, 104, 100, 100, 100, 97, 96, 98, 103, 101, 99, 96, 93, 90, 84, 79, 72, 71, 75, 75, 75, 75, 76, 75, 74, 72, 72, 73, 75, 77, 78, 78, 75, 72, 67, 63, 61, 64, 64, 63, 63, 60, 58, 58, 58, 59, 62, 61, 63, 66, 71, 69, 68, 69, 69, 68, 69, 73, 70, 61, 61, 61, 57, 52, 51, 55, 58, 64, 65, 63, 65, 70, 77, 80, 83, 80, 77, 80, 83, 89, 92, 96, 100, 98, 99, 102, 103, 105, 111, 116, 117, 114, 114, 115, 120, 124, 129, 134, 134, 141, 145, 142, 140, 144, 151, 150, 150, 154, 154, 153, 148, 149, 152, 149, 151, 150, 150, 151, 152, 151, 152, 150, 150, 152, 147, 144, 142, 147, 150, 150, 148, 146, 145, 146, 143, 137, 134, 134, 133, 128, 125, 123, 121, 113, 102, 99, 97, 96, 96, 96, 95, 94, 91, 94, 91, 90, 92, 95, 95, 93, 91, 88, 89, 89, 88, 88, 88, 88, 83, 79, 77, 75, 71, 70, 71, 73, 78, 79, 78, 75, 77, 78, 69, 61, 52, 44, 37, 29, 30, 32, 39, 44, 49, 47, 46, 44, 44, 48, 51, 53, 55, 58, 54, 49, 52, 58, 59, 58, 58, 58, 56, 57, 58, 60, 58, 61, 64, 64, 64, 63, 61, 61, 62, 62, 57, 58, 59, 63, 67, 68, 67, 70, 71, 71, 78, 82, 79, 80, 79, 80, 88, 93, 96, 99, 98, 96, 98, 94, 91, 93, 97, 95, 87, 89, 90, 92, 96, 99, 103, 105, 106, 106, 104, 102, 103, 103, 99, 97, 95, 93, 87, 79, 79, 82, 83, 83, 77, 77, 78, 73, 68, 65, 66, 65, 63, 62, 61, 64, 63, 64, 63, 60, 57, 57, 57, 53, 50, 49, 48, 48, 48, 45, 44, 42, 38, 37, 35, 36, 39, 45, 50, 46, 46, 51, 53, 55, 58, 59, 58, 57, 58, 63, 64, 65, 63, 62, 62, 66, 68, 69, 69, 67, 66, 67, 67, 65, 63, 61, 61, 58, 55, 52, 47, 43, 39, 37, 37, 36, 33, 30, 29, 25, 24, 21, 17, 13, 12, 9, 8, 9, 9, 10, 10, 9, 9, 8, 8, 8, 8, 8, 8, 8, 7, 7, 8, 8, 9, 7, 7, 7 }        -- feet, one per second from release

-- ------------------------------------------------ logging (read afterwards from this folder)
local DIR = "SCRIPTS:/NiceSim3_NoBadge/"
local lines = {}
local function flush()
  local ok, f = pcall(io.open, DIR .. "log.txt", "w")
  if ok and f then f:write(table.concat(lines, "\n") .. "\n"); f:close() end
end
local function log(s) lines[#lines + 1] = tostring(s); print("NiceSim: " .. tostring(s)); flush() end
local function shot(name) pcall(simulator.screenshot, DIR .. name .. ".bmp") end
local function readback()
  local out = {}
  local ok, src = pcall(system.getSource, { category = CATEGORY_TELEMETRY_SENSOR, name = "Altitude" })
  if ok and src then
    local _, v = pcall(function() return src:value() end)
    local _, a = pcall(function() return src:age() end)
    out[#out + 1] = "Altitude=" .. tostring(v) .. " age=" .. tostring(a)
  end
  local ok2, fmSrc = pcall(system.getSource, { category = CATEGORY_FLIGHT, member = 0 })
  if ok2 and fmSrc then local _, v = pcall(function() return fmSrc:value() end); out[#out + 1] = "fm=" .. tostring(v) end
  return table.concat(out, " ")
end

local function ctl(what, fn, ...)
  local ok, err = pcall(fn, ...)
  if not ok then log(what .. " FAILED (" .. tostring(err) .. ") -- do it by hand") end
end
local function launch(on)   ctl("launch switch", simulator.setSwitch, SW_LAUNCH, on and 100 or -100) end
local function elevator(v)  ctl("elevator", simulator.setAnalog, AN_ELEVATOR, v) end
local function throttle(v)  ctl("throttle/brake", simulator.setAnalog, AN_THROTTLE, v) end

local function frame(appId, value)
  simulator.injectSPortFrame({ module = 0, band = 0, rx = 0, physId = PHYS_ID, primId = 0x10, appId = appId, value = value })
end
local function send(ft)
  frame(RSSI_APP_ID, 90)
  frame(VFR_APP_ID, 100)
  frame(ALT_APP_ID, math.floor(ft * 30.48 + 0.5))                         -- S.Port altitude is centimetres
  frame(RX_APP_ID, RX_CV)
end
-- stream from ft towards nextFt for REAL seconds, a frame every FRAME_GAP
local lastLog, reads, lostReads = 0, 0, 0
local function sensorAlive()
  local ok, src = pcall(system.getSource, { category = CATEGORY_TELEMETRY_SENSOR, name = "Altitude" })
  if not (ok and src) then return true end
  local _, a = pcall(function() return src:age() end)
  return type(a) == "number" and a >= 0 and a < 1000
end
local function stream(ft, nextFt, seconds, tag)
  local n = math.max(1, math.floor(seconds / FRAME_GAP + 0.5))
  for i = 0, n - 1 do
    send(ft + (nextFt - ft) * i / n)
    simulator.sleep(seconds / n)
  end
  if tag then
    reads = reads + 1
    if not sensorAlive() then lostReads = lostReads + 1 end
    -- still dropping out? send frames more densely, down to every 10 ms
    if reads >= 8 then
      if lostReads >= 2 and FRAME_GAP > 0.011 then
        FRAME_GAP = math.max(0.01, FRAME_GAP * 0.6)
        log(string.format("sensor lost in %d of %d reads -> frame gap now %.3f s", lostReads, reads, FRAME_GAP))
      end
      reads, lostReads = 0, 0
    end
    if os.time() - lastLog >= 5 then lastLog = os.time(); log(tag .. " sent=" .. math.floor(nextFt) .. " ft | " .. readback()) end
  end
end

do
  local v = system.getVersion and system.getVersion() or {}
  local parts = {}
  for k, x in pairs(v) do parts[#parts + 1] = tostring(k) .. "=" .. tostring(x) end
  table.sort(parts)
  log("NiceSim3_NoBadge -- 6:47 of flight at SPEED " .. SPEED .. " | getVersion: " .. table.concat(parts, " "))
end
shot("s0_start")
throttle(100)                                  -- brake OFF first: at rest the model sits in Landing mode
stream(0, 0, 2)
shot("s1_throttle_up")                         -- the s* shots show which step (if any) flips the screen page
log("before launch | " .. readback())
launch(true)                                   -- launch button down: Launch mode, SF11 zeroes the altitude
stream(0, 0, 1)
shot("s2_launch_down")
-- The pilot's model had special functions that switched the screen page on
-- the launch switch (found via the step screenshots, 2026-09-17); he disabled
-- them. If a model still does that, PAGE presses (raw key index 0) WHILE THE
-- BUTTON IS HELD can steer the release back onto the widget's page.
local PAGE_PRESSES_WHILE_HELD = 0
for _ = 1, PAGE_PRESSES_WHILE_HELD do
  pcall(simulator.pressKey, 0, 0.1)
  stream(0, 0, 0.4)
end
log("button held   | " .. readback())
launch(false)                                  -- release: Zoom, the flight starts
-- The button holds the Altitude sensor in reset and the FIRST frame after
-- release becomes its zero: a few ground frames, but no more, because at
-- SPEED 8 every real second here is eight seconds of flight at 0 ft.
stream(0, 0, 0.15)
log("released      | " .. readback())
local pushAt = math.max(2, math.ceil(1.0 * SPEED))            -- about 1 real second after release
local pushEnd = pushAt + math.max(1, math.ceil(0.5 * SPEED))
local shots = { [math.floor(#ALT * 0.4)] = "1_live", [math.floor(#ALT * 0.85)] = "2_live_late" }
for i = 1, #ALT do
  if i == pushAt then elevator(40) end          -- leave Zoom, as the pilot did
  if i == pushEnd then elevator(0) end
  stream(ALT[i], ALT[i + 1] or ALT[i], 1 / SPEED, string.format("t=%d:%02d", math.floor(i / 60), i % 60))
  if i == pushEnd + 1 then shot("s3_in_flight_page") end
  if shots[i] then shot(shots[i]) end
end
elevator(0)
if BRAKED then
  log("BRAKE on | " .. readback())
  throttle(-100)
  stream(0, 0, 4)
  log("braked 4 s | " .. readback())
  throttle(100)
else
  log("hand catch, no brake: the widget ends the flight after 20 s on the ground")
  stream(0, 0, math.max(5, 28 / SPEED))
end
stream(0, 0, 4)                                -- long enough for the landing alert and the recap
shot("3_after_landing")
-- Walk the screen pages with the PAGE key (raw key index 0) and photograph
-- each, so the Nice Flight! page is captured even if the radio left it.
for n = 1, 3 do
  local ok, e = pcall(simulator.pressKey, 0, 0.1)
  if not ok then log("pressKey(PAGE) failed: " .. tostring(e)) break end
  stream(0, 0, 0.8)
  shot("p" .. n .. "_page")
end
log("done | " .. readback())
