-- NiceSim1_NearMiss -- Nice Flight! simulator macro, generated by tools/make_macros.py
-- from a REAL flight: BULL-NOSE-2026-09-16-11-31-28.csv (flight starting at 1966 s).
-- 275 ft, 3:55. Just under both bars: NOT a nice flight, no recap.
--
-- Run: FrSky Suite toolbar > Run Macro > pick THIS folder, then click Resume
-- (the debugger pauses on line 1). If it asks to restart the simulator to
-- load the files, click CANCEL. Have the Nice Flight! page showing.
--
-- SPEED: how much faster than real life the flight is replayed. The widget
-- must run its flight clock at the SAME rate or the flight will be measured
-- short: Nice Flight! CFG > Data > Simulator time scale = SPEED (1, 4, 8 or
-- 16). At 8x this 4:01 flight takes about 42 seconds. Set both to 1
-- to watch the Live screen in real time.
local SPEED = 8

-- Controls, as MEASURED in the simulator with sim/NiceSimDiag (2026-09-17,
-- X14, Ethos 26.1.2), reading the real sources back after each call:
--   simulator.setAnalog(1, v)  = throttle. At rest (0) the template reads the
--                                brake as pulled = Landing mode; +100 = brake off.
--   simulator.setAnalog(2, v)  = elevator (any movement leaves Zoom)
--   simulator.setSwitch(7, v)  = the launch button: +100 -> Launch mode,
--                                -100 -> Zoom until the elevator moves.
local AN_THROTTLE, AN_ELEVATOR, SW_LAUNCH = 1, 2, 7

-- Telemetry. Any module/band/rx/physId reaches the model's Altitude sensor,
-- but the simulator flags every sensor LOST within ~0.25 s unless the radio
-- link looks alive, so RSSI and VFR frames go out with every altitude frame
-- and frames never stop for longer than FRAME_GAP real seconds (at 0.1 s the
-- sensor still flapped between alive and lost; measured 2026-09-17).
local PHYS_ID = 0x1A
local ALT_APP_ID, RX_APP_ID, RSSI_APP_ID, VFR_APP_ID = 0x0100, 0xF104, 0xF101, 0xF010
local RX_CV = 500
local FRAME_GAP = 0.03           -- tightened automatically if the sensor still drops out

local BRAKED = false        -- false = hand catch: the widget ends it after 20 s on the ground
local ALT = { 10, 63, 104, 109, 105, 107, 108, 108, 108, 108, 105, 106, 107, 107, 108, 110, 113, 117, 116, 118, 122, 123, 125, 128, 135, 139, 143, 146, 146, 149, 152, 159, 163, 167, 169, 172, 177, 180, 182, 189, 191, 195, 199, 204, 205, 208, 213, 216, 219, 222, 222, 224, 226, 229, 231, 230, 236, 238, 242, 248, 252, 250, 252, 256, 261, 265, 264, 266, 265, 269, 271, 274, 274, 270, 266, 265, 265, 260, 257, 256, 255, 250, 246, 238, 230, 225, 224, 226, 227, 222, 215, 211, 205, 200, 193, 189, 187, 185, 183, 180, 175, 171, 164, 160, 153, 135, 130, 133, 138, 144, 145, 140, 138, 135, 132, 127, 122, 118, 114, 109, 104, 101, 99, 92, 87, 84, 81, 81, 79, 76, 75, 71, 72, 72, 65, 62, 61, 62, 64, 65, 68, 70, 71, 73, 75, 79, 74, 72, 76, 77, 77, 75, 76, 77, 79, 75, 77, 82, 81, 76, 78, 82, 80, 79, 77, 77, 76, 77, 76, 77, 76, 77, 78, 75, 73, 73, 72, 71, 72, 71, 73, 77, 80, 81, 80, 79, 80, 87, 95, 105, 109, 102, 100, 102, 102, 100, 100, 100, 95, 87, 90, 86, 77, 75, 75, 77, 79, 75, 77, 77, 78, 73, 67, 65, 63, 61, 56, 52, 49, 45, 43, 46, 47, 45, 44, 43, 44, 41, 40, 38, 34, 29, 28, 28, 24, 21, 15, 9, 6, 6, 4 }        -- feet, one per second from release

-- ------------------------------------------------ logging (read afterwards from this folder)
local DIR = "SCRIPTS:/NiceSim1_NearMiss/"
local lines = {}
local function flush()
  local ok, f = pcall(io.open, DIR .. "log.txt", "w")
  if ok and f then f:write(table.concat(lines, "\n") .. "\n"); f:close() end
end
local function log(s) lines[#lines + 1] = tostring(s); print("NiceSim: " .. tostring(s)); flush() end
local function shot(name) pcall(simulator.screenshot, DIR .. name .. ".bmp") end
local function readback()
  local out = {}
  local ok, src = pcall(system.getSource, { category = CATEGORY_TELEMETRY_SENSOR, name = "Altitude" })
  if ok and src then
    local _, v = pcall(function() return src:value() end)
    local _, a = pcall(function() return src:age() end)
    out[#out + 1] = "Altitude=" .. tostring(v) .. " age=" .. tostring(a)
  end
  local ok2, fmSrc = pcall(system.getSource, { category = CATEGORY_FLIGHT, member = 0 })
  if ok2 and fmSrc then local _, v = pcall(function() return fmSrc:value() end); out[#out + 1] = "fm=" .. tostring(v) end
  return table.concat(out, " ")
end

local function ctl(what, fn, ...)
  local ok, err = pcall(fn, ...)
  if not ok then log(what .. " FAILED (" .. tostring(err) .. ") -- do it by hand") end
end
local function launch(on)   ctl("launch switch", simulator.setSwitch, SW_LAUNCH, on and 100 or -100) end
local function elevator(v)  ctl("elevator", simulator.setAnalog, AN_ELEVATOR, v) end
local function throttle(v)  ctl("throttle/brake", simulator.setAnalog, AN_THROTTLE, v) end

local function frame(appId, value)
  simulator.injectSPortFrame({ module = 0, band = 0, rx = 0, physId = PHYS_ID, primId = 0x10, appId = appId, value = value })
end
local function send(ft)
  frame(RSSI_APP_ID, 90)
  frame(VFR_APP_ID, 100)
  frame(ALT_APP_ID, math.floor(ft * 30.48 + 0.5))                         -- S.Port altitude is centimetres
  frame(RX_APP_ID, RX_CV)
end
-- stream from ft towards nextFt for REAL seconds, a frame every FRAME_GAP
local lastLog, reads, lostReads = 0, 0, 0
local function sensorAlive()
  local ok, src = pcall(system.getSource, { category = CATEGORY_TELEMETRY_SENSOR, name = "Altitude" })
  if not (ok and src) then return true end
  local _, a = pcall(function() return src:age() end)
  return type(a) == "number" and a >= 0 and a < 1000
end
local function stream(ft, nextFt, seconds, tag)
  local n = math.max(1, math.floor(seconds / FRAME_GAP + 0.5))
  for i = 0, n - 1 do
    send(ft + (nextFt - ft) * i / n)
    simulator.sleep(seconds / n)
  end
  if tag then
    reads = reads + 1
    if not sensorAlive() then lostReads = lostReads + 1 end
    -- still dropping out? send frames more densely, down to every 10 ms
    if reads >= 8 then
      if lostReads >= 2 and FRAME_GAP > 0.011 then
        FRAME_GAP = math.max(0.01, FRAME_GAP * 0.6)
        log(string.format("sensor lost in %d of %d reads -> frame gap now %.3f s", lostReads, reads, FRAME_GAP))
      end
      reads, lostReads = 0, 0
    end
    if os.time() - lastLog >= 5 then lastLog = os.time(); log(tag .. " sent=" .. math.floor(nextFt) .. " ft | " .. readback()) end
  end
end

do
  local v = system.getVersion and system.getVersion() or {}
  local parts = {}
  for k, x in pairs(v) do parts[#parts + 1] = tostring(k) .. "=" .. tostring(x) end
  table.sort(parts)
  log("NiceSim1_NearMiss -- 4:01 of flight at SPEED " .. SPEED .. " | getVersion: " .. table.concat(parts, " "))
end
shot("s0_start")
throttle(100)                                  -- brake OFF first: at rest the model sits in Landing mode
stream(0, 0, 2)
shot("s1_throttle_up")                         -- the s* shots show which step (if any) flips the screen page
log("before launch | " .. readback())
launch(true)                                   -- launch button down: Launch mode, SF11 zeroes the altitude
stream(0, 0, 1)
shot("s2_launch_down")
-- The pilot's model had special functions that switched the screen page on
-- the launch switch (found via the step screenshots, 2026-09-17); he disabled
-- them. If a model still does that, PAGE presses (raw key index 0) WHILE THE
-- BUTTON IS HELD can steer the release back onto the widget's page.
local PAGE_PRESSES_WHILE_HELD = 0
for _ = 1, PAGE_PRESSES_WHILE_HELD do
  pcall(simulator.pressKey, 0, 0.1)
  stream(0, 0, 0.4)
end
log("button held   | " .. readback())
launch(false)                                  -- release: Zoom, the flight starts
-- The button holds the Altitude sensor in reset and the FIRST frame after
-- release becomes its zero: a few ground frames, but no more, because at
-- SPEED 8 every real second here is eight seconds of flight at 0 ft.
stream(0, 0, 0.15)
log("released      | " .. readback())
local pushAt = math.max(2, math.ceil(1.0 * SPEED))            -- about 1 real second after release
local pushEnd = pushAt + math.max(1, math.ceil(0.5 * SPEED))
local shots = { [math.floor(#ALT * 0.4)] = "1_live", [math.floor(#ALT * 0.85)] = "2_live_late" }
for i = 1, #ALT do
  if i == pushAt then elevator(40) end          -- leave Zoom, as the pilot did
  if i == pushEnd then elevator(0) end
  stream(ALT[i], ALT[i + 1] or ALT[i], 1 / SPEED, string.format("t=%d:%02d", math.floor(i / 60), i % 60))
  if i == pushEnd + 1 then shot("s3_in_flight_page") end
  if shots[i] then shot(shots[i]) end
end
elevator(0)
if BRAKED then
  log("BRAKE on | " .. readback())
  throttle(-100)
  stream(0, 0, 4)
  log("braked 4 s | " .. readback())
  throttle(100)
else
  log("hand catch, no brake: the widget ends the flight after 20 s on the ground")
  stream(0, 0, math.max(5, 28 / SPEED))
end
stream(0, 0, 4)                                -- long enough for the landing alert and the recap
shot("3_after_landing")
-- Walk the screen pages with the PAGE key (raw key index 0) and photograph
-- each, so the Nice Flight! page is captured even if the radio left it.
for n = 1, 3 do
  local ok, e = pcall(simulator.pressKey, 0, 0.1)
  if not ok then log("pressKey(PAGE) failed: " .. tostring(e)) break end
  stream(0, 0, 0.8)
  shot("p" .. n .. "_page")
end
log("done | " .. readback())
