"""Builds FrSky Suite simulator macros that replay REAL flights from Ethos
telemetry logs, plus sim/flights.json for harness/macro_check.py.

    python3 tools/make_macros.py /path/to/logs     # folder holding the CSVs

Each macro lives in its own folder (Run Macro executes every .lua in the
folder it is pointed at), is self-contained, and replays: ground frames, the
launch button (switch SG) held and released, an elevator push to leave Zoom,
the logged altitude once a second (sent 4x a second so the sensor never goes
stale), then either the brake (throttle stick) or, for a hand catch, ground
frames until the widget's own 20 s ground rule ends the flight.
"""
import csv, json, os, sys
from datetime import datetime

SPEED = 8          # default replay speed written into the macros
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "sim")

# (folder, log file, flight start second as reported by harness/replay.py, what it should do)
FLIGHTS = [
    ("NiceSim1_NearMiss",   "BULL-NOSE-2026-09-16-11-31-28.csv", 1966, "275 ft, 3:55. Just under both bars: NOT a nice flight, no recap."),
    ("NiceSim2_Duration",   "BULL-NOSE-2026-09-16-11-31-28.csv", 1056, "379 ft, 5:15. Nice; on a clean slate earns the Duration 5 min first, nothing else."),
    ("NiceSim3_NoBadge",    "BULL-NOSE-2026-09-16-14-29-06.csv",  685, "155 ft, 6:23. Nice by time. Run AFTER NiceSim2: Duration 5 is already held, so NO badges."),
    ("NiceSim4_SavePeak",   "BULL-NOSE-2026-09-16-14-29-06.csv", 1233, "440 ft, 7:52, dipped to 49 ft then climbed out. Peak 400 + Save (the 50 rung) + Record height. Hand catch, no brake."),
    ("NiceSim5_Epic",       "BULL-NOSE-2026-09-15-10-50-42.csv", 1013, "475 ft, 16:04, five climbs. Duration, Yo-yo, Rebound and both Records (its low of 87 ft is not under 60, so no Save). Long: 16 minutes."),
]

def load(path):
    rd = csv.reader(open(path, newline="", encoding="utf-8", errors="replace"))
    h = next(rd)
    def find(s): return next(i for i, n in enumerate(h) if s in n)
    ia, il, ib, ir = find("Altitude"), find("MOM_LAUNCH"), find("LANDING_MODE"), find("RxBatt")
    metric = "(m)" in h[ia]
    rows, t0 = [], None
    for r in rd:
        if len(r) < 10: continue
        try: ts = datetime.strptime(r[0] + " " + r[1], "%Y-%m-%d %H:%M:%S.%f")
        except ValueError: continue
        t0 = t0 or ts
        def v(i):
            try: return float(r[i]) if r[i] != "" else None
            except (ValueError, IndexError): return None
        alt = v(ia)
        if alt is not None and metric: alt *= 3.28084
        rows.append(((ts - t0).total_seconds(), alt, (v(il) or 0) > 0, (v(ib) or 0) > 0, v(ir)))
    return rows

def extract(rows, start):
    # the release is the MOM_LAUNCH falling edge nearest `start`; the press is the rising edge before it
    rel = min((i for i in range(1, len(rows)) if rows[i - 1][2] and not rows[i][2]), key=lambda i: abs(rows[i][0] - start))
    prs = rel
    while prs > 0 and rows[prs - 1][2]: prs -= 1
    hold = max(1.0, min(4.0, rows[rel][0] - rows[prs][0]))
    tRel = rows[rel][0]
    # the flight runs until the next launch press or the end of the log
    end = next((i for i in range(rel + 1, len(rows)) if rows[i][2]), len(rows))
    seg = rows[rel:end]
    # 1 Hz altitude, holding the last good value across telemetry gaps
    alts, last, sec = [], 0.0, 0
    for t, alt, L, B, rx in seg:
        if alt is not None: last = alt
        while t - tRel >= sec: alts.append(round(max(last, 0.0), 1)); sec += 1
    # stop once it has been on the ground (< 8 ft) for 3 s after having flown
    flown, low, cut = False, 0, len(alts)
    for i, a in enumerate(alts):
        if a > 40: flown = True
        low = low + 1 if (flown and a < 8) else 0
        if low >= 3: cut = i + 1; break
    alts = alts[:cut]
    # did the pilot brake to land? (LANDING_MODE held >= 1 s in the last 15 s of the flight)
    tEnd = tRel + len(alts)
    brake = [t for t, alt, L, B, rx in seg if B and tEnd - 15 <= t <= tEnd + 3]
    braked = len(brake) >= 4
    brakeAt = int(min(brake) - tRel) if braked else None
    rxv = next((rx for t, alt, L, B, rx in seg if rx), 3.8)
    return { "hold": round(hold, 1), "alts": alts, "braked": braked, "brakeAt": brakeAt, "rxv": rxv }

MACRO = r'''-- %(name)s -- Nice Flight! simulator macro, generated by tools/make_macros.py
-- from a REAL flight: %(log)s (flight starting at %(start)d s).
-- %(what)s
--
-- Run: FrSky Suite toolbar > Run Macro > pick THIS folder, then click Resume
-- (the debugger pauses on line 1). If it asks to restart the simulator to
-- load the files, click CANCEL. Have the Nice Flight! page showing.
--
-- SPEED: how much faster than real life the flight is replayed. The widget
-- must run its flight clock at the SAME rate or the flight will be measured
-- short: Nice Flight! CFG > Data > Simulator time scale = SPEED (1, 4, 8 or
-- 16). At 8x this %(mmss)s flight takes about %(real8)d seconds. Set both to 1
-- to watch the Live screen in real time.
local SPEED = %(speed)d

-- Controls, as MEASURED in the simulator with sim/NiceSimDiag (2026-09-17,
-- X14, Ethos 26.1.2), reading the real sources back after each call:
--   simulator.setAnalog(1, v)  = throttle. At rest (0) the template reads the
--                                brake as pulled = Landing mode; +100 = brake off.
--   simulator.setAnalog(2, v)  = elevator (any movement leaves Zoom)
--   simulator.setSwitch(7, v)  = the launch button: +100 -> Launch mode,
--                                -100 -> Zoom until the elevator moves.
local AN_THROTTLE, AN_ELEVATOR, SW_LAUNCH = 1, 2, 7

-- Telemetry. Any module/band/rx/physId reaches the model's Altitude sensor,
-- but the simulator flags every sensor LOST within ~0.25 s unless the radio
-- link looks alive, so RSSI and VFR frames go out with every altitude frame
-- and frames never stop for longer than FRAME_GAP real seconds (at 0.1 s the
-- sensor still flapped between alive and lost; measured 2026-09-17).
local PHYS_ID = 0x1A
local ALT_APP_ID, RX_APP_ID, RSSI_APP_ID, VFR_APP_ID = 0x0100, 0xF104, 0xF101, 0xF010
local RX_CV = %(rxcv)d
local FRAME_GAP = 0.03           -- tightened automatically if the sensor still drops out

local BRAKED = %(braked)s        -- false = hand catch: the widget ends it after 20 s on the ground
local ALT = { %(alts)s }        -- feet, one per second from release

-- ------------------------------------------------ logging (read afterwards from this folder)
local DIR = "SCRIPTS:/%(name)s/"
local lines = {}
local function flush()
  local ok, f = pcall(io.open, DIR .. "log.txt", "w")
  if ok and f then f:write(table.concat(lines, "\n") .. "\n"); f:close() end
end
local function log(s) lines[#lines + 1] = tostring(s); print("NiceSim: " .. tostring(s)); flush() end
local function shot(name) pcall(simulator.screenshot, DIR .. name .. ".bmp") end
local function readback()
  local out = {}
  local ok, src = pcall(system.getSource, { category = CATEGORY_TELEMETRY_SENSOR, name = "Altitude" })
  if ok and src then
    local _, v = pcall(function() return src:value() end)
    local _, a = pcall(function() return src:age() end)
    out[#out + 1] = "Altitude=" .. tostring(v) .. " age=" .. tostring(a)
  end
  local ok2, fmSrc = pcall(system.getSource, { category = CATEGORY_FLIGHT, member = 0 })
  if ok2 and fmSrc then local _, v = pcall(function() return fmSrc:value() end); out[#out + 1] = "fm=" .. tostring(v) end
  return table.concat(out, " ")
end

local function ctl(what, fn, ...)
  local ok, err = pcall(fn, ...)
  if not ok then log(what .. " FAILED (" .. tostring(err) .. ") -- do it by hand") end
end
local function launch(on)   ctl("launch switch", simulator.setSwitch, SW_LAUNCH, on and 100 or -100) end
local function elevator(v)  ctl("elevator", simulator.setAnalog, AN_ELEVATOR, v) end
local function throttle(v)  ctl("throttle/brake", simulator.setAnalog, AN_THROTTLE, v) end

local function frame(appId, value)
  simulator.injectSPortFrame({ module = 0, band = 0, rx = 0, physId = PHYS_ID, primId = 0x10, appId = appId, value = value })
end
local function send(ft)
  frame(RSSI_APP_ID, 90)
  frame(VFR_APP_ID, 100)
  frame(ALT_APP_ID, math.floor(ft * 30.48 + 0.5))                         -- S.Port altitude is centimetres
  frame(RX_APP_ID, RX_CV)
end
-- stream from ft towards nextFt for REAL seconds, a frame every FRAME_GAP
local lastLog, reads, lostReads = 0, 0, 0
local function sensorAlive()
  local ok, src = pcall(system.getSource, { category = CATEGORY_TELEMETRY_SENSOR, name = "Altitude" })
  if not (ok and src) then return true end
  local _, a = pcall(function() return src:age() end)
  return type(a) == "number" and a >= 0 and a < 1000
end
local function stream(ft, nextFt, seconds, tag)
  local n = math.max(1, math.floor(seconds / FRAME_GAP + 0.5))
  for i = 0, n - 1 do
    send(ft + (nextFt - ft) * i / n)
    simulator.sleep(seconds / n)
  end
  if tag then
    reads = reads + 1
    if not sensorAlive() then lostReads = lostReads + 1 end
    -- still dropping out? send frames more densely, down to every 10 ms
    if reads >= 8 then
      if lostReads >= 2 and FRAME_GAP > 0.011 then
        FRAME_GAP = math.max(0.01, FRAME_GAP * 0.6)
        log(string.format("sensor lost in %%d of %%d reads -> frame gap now %%.3f s", lostReads, reads, FRAME_GAP))
      end
      reads, lostReads = 0, 0
    end
    if os.time() - lastLog >= 5 then lastLog = os.time(); log(tag .. " sent=" .. math.floor(nextFt) .. " ft | " .. readback()) end
  end
end

do
  local v = system.getVersion and system.getVersion() or {}
  local parts = {}
  for k, x in pairs(v) do parts[#parts + 1] = tostring(k) .. "=" .. tostring(x) end
  table.sort(parts)
  log("%(name)s -- %(mmss)s of flight at SPEED " .. SPEED .. " | getVersion: " .. table.concat(parts, " "))
end
shot("s0_start")
throttle(100)                                  -- brake OFF first: at rest the model sits in Landing mode
stream(0, 0, 2)
shot("s1_throttle_up")                         -- the s* shots show which step (if any) flips the screen page
log("before launch | " .. readback())
launch(true)                                   -- launch button down: Launch mode, SF11 zeroes the altitude
stream(0, 0, 1)
shot("s2_launch_down")
-- The pilot's model had special functions that switched the screen page on
-- the launch switch (found via the step screenshots, 2026-09-17); he disabled
-- them. If a model still does that, PAGE presses (raw key index 0) WHILE THE
-- BUTTON IS HELD can steer the release back onto the widget's page.
local PAGE_PRESSES_WHILE_HELD = 0
for _ = 1, PAGE_PRESSES_WHILE_HELD do
  pcall(simulator.pressKey, 0, 0.1)
  stream(0, 0, 0.4)
end
log("button held   | " .. readback())
launch(false)                                  -- release: Zoom, the flight starts
-- The button holds the Altitude sensor in reset and the FIRST frame after
-- release becomes its zero: a few ground frames, but no more, because at
-- SPEED 8 every real second here is eight seconds of flight at 0 ft.
stream(0, 0, 0.15)
log("released      | " .. readback())
local pushAt = math.max(2, math.ceil(1.0 * SPEED))            -- about 1 real second after release
local pushEnd = pushAt + math.max(1, math.ceil(0.5 * SPEED))
local shots = { [math.floor(#ALT * 0.4)] = "1_live", [math.floor(#ALT * 0.85)] = "2_live_late" }
for i = 1, #ALT do
  if i == pushAt then elevator(40) end          -- leave Zoom, as the pilot did
  if i == pushEnd then elevator(0) end
  stream(ALT[i], ALT[i + 1] or ALT[i], 1 / SPEED, string.format("t=%%d:%%02d", math.floor(i / 60), i %% 60))
  if i == pushEnd + 1 then shot("s3_in_flight_page") end
  if shots[i] then shot(shots[i]) end
end
elevator(0)
if BRAKED then
  log("BRAKE on | " .. readback())
  throttle(-100)
  stream(0, 0, 4)
  log("braked 4 s | " .. readback())
  throttle(100)
else
  log("hand catch, no brake: the widget ends the flight after 20 s on the ground")
  stream(0, 0, math.max(5, 28 / SPEED))
end
stream(0, 0, 4)                                -- long enough for the landing alert and the recap
shot("3_after_landing")
-- Walk the screen pages with the PAGE key (raw key index 0) and photograph
-- each, so the Nice Flight! page is captured even if the radio left it.
for n = 1, 3 do
  local ok, e = pcall(simulator.pressKey, 0, 0.1)
  if not ok then log("pressKey(PAGE) failed: " .. tostring(e)) break end
  stream(0, 0, 0.8)
  shot("p" .. n .. "_page")
end
log("done | " .. readback())
'''

def main(logdir):
    meta = []
    for name, log, start, what in FLIGHTS:
        f = extract(load(os.path.join(logdir, log)), start)
        d = os.path.join(OUT, name); os.makedirs(d, exist_ok=True)
        alts = ", ".join(("%g" % a) for a in f["alts"])
        open(os.path.join(d, "flight.lua"), "w").write(MACRO % {
            "name": name, "log": log, "start": start, "what": what, "speed": SPEED,
            "mmss": "%d:%02d" % (len(f["alts"]) // 60, len(f["alts"]) % 60), "real8": len(f["alts"]) // 8 + 12,
            "braked": "true" if f["braked"] else "false", "alts": alts, "nsec": len(f["alts"]),
            "rxcv": int(round(f["rxv"] * 100)) })
        meta.append({ "name": name, "what": what, **f })
        print("%-20s %4d s  max %3d ft  hold %.1f s  %s" % (name, len(f["alts"]), max(f["alts"]), f["hold"],
              "brake at %d s" % f["brakeAt"] if f["braked"] else "hand catch"))
    json.dump(meta, open(os.path.join(OUT, "flights.json"), "w"))

if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else os.path.join(OUT, "logs"))
